//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCValidator.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_sv {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_sv() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DGCValidator.Resources.AppResources.sv", typeof(AppResources_sv).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        public static string InformationHeader {
            get {
                return ResourceManager.GetString("InformationHeader", resourceCulture);
            }
        }
        
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        public static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        public static string ScanAgainButtonText {
            get {
                return ResourceManager.GetString("ScanAgainButtonText", resourceCulture);
            }
        }
        
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        public static string ScanTopText {
            get {
                return ResourceManager.GetString("ScanTopText", resourceCulture);
            }
        }
        
        public static string ScanBottomText {
            get {
                return ResourceManager.GetString("ScanBottomText", resourceCulture);
            }
        }
        
        public static string ScanFlashText {
            get {
                return ResourceManager.GetString("ScanFlashText", resourceCulture);
            }
        }
        
        public static string ScanCancelText {
            get {
                return ResourceManager.GetString("ScanCancelText", resourceCulture);
            }
        }
        
        public static string IssuedDateLabel {
            get {
                return ResourceManager.GetString("IssuedDateLabel", resourceCulture);
            }
        }
        
        public static string ExpireDateLabel {
            get {
                return ResourceManager.GetString("ExpireDateLabel", resourceCulture);
            }
        }
        
        public static string VaccinatedText {
            get {
                return ResourceManager.GetString("VaccinatedText", resourceCulture);
            }
        }
        
        public static string NotFullyVaccinatedText {
            get {
                return ResourceManager.GetString("NotFullyVaccinatedText", resourceCulture);
            }
        }
        
        public static string TestedText {
            get {
                return ResourceManager.GetString("TestedText", resourceCulture);
            }
        }
        
        public static string RecoveredText {
            get {
                return ResourceManager.GetString("RecoveredText", resourceCulture);
            }
        }
        
        public static string MissingDataText {
            get {
                return ResourceManager.GetString("MissingDataText", resourceCulture);
            }
        }
        
        public static string ErrorReadingText {
            get {
                return ResourceManager.GetString("ErrorReadingText", resourceCulture);
            }
        }
        
        public static string ApprovedHeader {
            get {
                return ResourceManager.GetString("ApprovedHeader", resourceCulture);
            }
        }
        
        public static string NotApprovedHeader {
            get {
                return ResourceManager.GetString("NotApprovedHeader", resourceCulture);
            }
        }
        
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        public static string FirstnameLabel {
            get {
                return ResourceManager.GetString("FirstnameLabel", resourceCulture);
            }
        }
        
        public static string FamilynameLabel {
            get {
                return ResourceManager.GetString("FamilynameLabel", resourceCulture);
            }
        }
        
        public static string TranNameLabel {
            get {
                return ResourceManager.GetString("TranNameLabel", resourceCulture);
            }
        }
        
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        public static string DiseaseLabel {
            get {
                return ResourceManager.GetString("DiseaseLabel", resourceCulture);
            }
        }
        
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        public static string IssuerLabel {
            get {
                return ResourceManager.GetString("IssuerLabel", resourceCulture);
            }
        }
        
        public static string CertificateIdentifierLabel {
            get {
                return ResourceManager.GetString("CertificateIdentifierLabel", resourceCulture);
            }
        }
        
        public static string TestHeader {
            get {
                return ResourceManager.GetString("TestHeader", resourceCulture);
            }
        }
        
        public static string TestTypeLabel {
            get {
                return ResourceManager.GetString("TestTypeLabel", resourceCulture);
            }
        }
        
        public static string TestNameLabel {
            get {
                return ResourceManager.GetString("TestNameLabel", resourceCulture);
            }
        }
        
        public static string TestManifacturerLabel {
            get {
                return ResourceManager.GetString("TestManifacturerLabel", resourceCulture);
            }
        }
        
        public static string TestSampleOriginLabel {
            get {
                return ResourceManager.GetString("TestSampleOriginLabel", resourceCulture);
            }
        }
        
        public static string TestResultLabel {
            get {
                return ResourceManager.GetString("TestResultLabel", resourceCulture);
            }
        }
        
        public static string TestingCentreLabel {
            get {
                return ResourceManager.GetString("TestingCentreLabel", resourceCulture);
            }
        }
        
        public static string TestDateLabel {
            get {
                return ResourceManager.GetString("TestDateLabel", resourceCulture);
            }
        }
        
        public static string TestResultDateLabel {
            get {
                return ResourceManager.GetString("TestResultDateLabel", resourceCulture);
            }
        }
        
        public static string ValidFromLabel {
            get {
                return ResourceManager.GetString("ValidFromLabel", resourceCulture);
            }
        }
        
        public static string ValidUntilLabel {
            get {
                return ResourceManager.GetString("ValidUntilLabel", resourceCulture);
            }
        }
        
        public static string RecoveryHeader {
            get {
                return ResourceManager.GetString("RecoveryHeader", resourceCulture);
            }
        }
        
        public static string RecTestDateLabel {
            get {
                return ResourceManager.GetString("RecTestDateLabel", resourceCulture);
            }
        }
        
        public static string VaccinationHeader {
            get {
                return ResourceManager.GetString("VaccinationHeader", resourceCulture);
            }
        }
        
        public static string DoseText {
            get {
                return ResourceManager.GetString("DoseText", resourceCulture);
            }
        }
        
        public static string VaccineDescriptionLabel {
            get {
                return ResourceManager.GetString("VaccineDescriptionLabel", resourceCulture);
            }
        }
        
        public static string VaccineNameLabel {
            get {
                return ResourceManager.GetString("VaccineNameLabel", resourceCulture);
            }
        }
        
        public static string VaccineAuthLabel {
            get {
                return ResourceManager.GetString("VaccineAuthLabel", resourceCulture);
            }
        }
        
        public static string VaccineLotLabel {
            get {
                return ResourceManager.GetString("VaccineLotLabel", resourceCulture);
            }
        }
        
        public static string VaccinationDateLabel {
            get {
                return ResourceManager.GetString("VaccinationDateLabel", resourceCulture);
            }
        }
        
        public static string VaccinationProviderLabel {
            get {
                return ResourceManager.GetString("VaccinationProviderLabel", resourceCulture);
            }
        }
        
        public static string AboutHeaderText {
            get {
                return ResourceManager.GetString("AboutHeaderText", resourceCulture);
            }
        }
        
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        public static string ProductionText {
            get {
                return ResourceManager.GetString("ProductionText", resourceCulture);
            }
        }
        
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        public static string VerificationText {
            get {
                return ResourceManager.GetString("VerificationText", resourceCulture);
            }
        }
        
        public static string NoVerificationText {
            get {
                return ResourceManager.GetString("NoVerificationText", resourceCulture);
            }
        }
    }
}
