//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGCValidator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGCValidator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string AboutHeaderText {
            get {
                return ResourceManager.GetString("AboutHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification app for EU Digital Covid Certificates (DCC), developed by the Agency for Digital Government (DIGG).
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel button.
        /// </summary>
        public static string AboutViewCancelButtonText {
            get {
                return ResourceManager.GetString("AboutViewCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIGG logotype.
        /// </summary>
        public static string AboutViewLogotypeText {
            get {
                return ResourceManager.GetString("AboutViewLogotypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string ApprovedHeader {
            get {
                return ResourceManager.GetString("ApprovedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date: .
        /// </summary>
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier: .
        /// </summary>
        public static string CertificateIdentifierLabel {
            get {
                return ResourceManager.GetString("CertificateIdentifierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: .
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccination certificate expired.
        /// </summary>
        public static string DCCExpired {
            get {
                return ResourceManager.GetString("DCCExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease: .
        /// </summary>
        public static string DiseaseLabel {
            get {
                return ResourceManager.GetString("DiseaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose .
        /// </summary>
        public static string DoseText {
            get {
                return ResourceManager.GetString("DoseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading.
        /// </summary>
        public static string ErrorReadingText {
            get {
                return ResourceManager.GetString("ErrorReadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire: .
        /// </summary>
        public static string ExpireDateLabel {
            get {
                return ResourceManager.GetString("ExpireDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name: .
        /// </summary>
        public static string FamilynameLabel {
            get {
                return ResourceManager.GetString("FamilynameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name: .
        /// </summary>
        public static string FirstnameLabel {
            get {
                return ResourceManager.GetString("FirstnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC.
        /// </summary>
        public static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator.
        /// </summary>
        public static string InformationHeader {
            get {
                return ResourceManager.GetString("InformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can validate a Covid certificate by scanning it with the camera.
        /// </summary>
        public static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signing certificate.
        /// </summary>
        public static string InvalidSigningCertificate {
            get {
                return ResourceManager.GetString("InvalidSigningCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued: .
        /// </summary>
        public static string IssuedDateLabel {
            get {
                return ResourceManager.GetString("IssuedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer: .
        /// </summary>
        public static string IssuerLabel {
            get {
                return ResourceManager.GetString("IssuerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect the app to internet and the keys will be downloaded automatically.
        /// </summary>
        public static string KeyModalErrorMessage {
            get {
                return ResourceManager.GetString("KeyModalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys retrived: .
        /// </summary>
        public static string KeyVersion {
            get {
                return ResourceManager.GetString("KeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use Vaccination certificate Verifier.
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture of a mobile device with a QR code.
        /// </summary>
        public static string MainViewImageText {
            get {
                return ResourceManager.GetString("MainViewImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info button.
        /// </summary>
        public static string MainViewInfoButtonText {
            get {
                return ResourceManager.GetString("MainViewInfoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string MissingDataText {
            get {
                return ResourceManager.GetString("MissingDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public keys.
        /// </summary>
        public static string NoPublicKeys {
            get {
                return ResourceManager.GetString("NoPublicKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signing certificate could be found.
        /// </summary>
        public static string NoSigningCertifcateCouldBeFound {
            get {
                return ResourceManager.GetString("NoSigningCertifcateCouldBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 14 days since last dose.
        /// </summary>
        public static string NotApprovedDaysSinceLastDose {
            get {
                return ResourceManager.GetString("NotApprovedDaysSinceLastDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid.
        /// </summary>
        public static string NotApprovedHeader {
            get {
                return ResourceManager.GetString("NotApprovedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than .
        /// </summary>
        public static string NotApprovedMaxDaysSinceLastDosePartOne {
            get {
                return ResourceManager.GetString("NotApprovedMaxDaysSinceLastDosePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days since the last vaccine dose.
        /// </summary>
        public static string NotApprovedMaxDaysSinceLastDosePartTwo {
            get {
                return ResourceManager.GetString("NotApprovedMaxDaysSinceLastDosePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fully vaccinated.
        /// </summary>
        public static string NotApprovedNoOfDoses {
            get {
                return ResourceManager.GetString("NotApprovedNoOfDoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid vaccination.
        /// </summary>
        public static string NotApprovedVaccine {
            get {
                return ResourceManager.GetString("NotApprovedVaccine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not fully vaccinated.
        /// </summary>
        public static string NotFullyVaccinatedText {
            get {
                return ResourceManager.GetString("NotFullyVaccinatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verification.
        /// </summary>
        public static string NoVerificationText {
            get {
                return ResourceManager.GetString("NoVerificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public keys are old.
        /// </summary>
        public static string OldPublicKeys {
            get {
                return ResourceManager.GetString("OldPublicKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("PrivacyPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string ProductionText {
            get {
                return ResourceManager.GetString("ProductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered.
        /// </summary>
        public static string RecoveredText {
            get {
                return ResourceManager.GetString("RecoveredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered.
        /// </summary>
        public static string RecoveryHeader {
            get {
                return ResourceManager.GetString("RecoveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive date: .
        /// </summary>
        public static string RecTestDateLabel {
            get {
                return ResourceManager.GetString("RecTestDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh trust list.
        /// </summary>
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid icon.
        /// </summary>
        public static string ResultViewFailedImageText {
            get {
                return ResourceManager.GetString("ResultViewFailedImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid icon.
        /// </summary>
        public static string ResultViewValidImageText {
            get {
                return ResourceManager.GetString("ResultViewValidImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraudulent certificate.
        /// </summary>
        public static string RevokedCertificateText {
            get {
                return ResourceManager.GetString("RevokedCertificateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate next.
        /// </summary>
        public static string ScanAgainButtonText {
            get {
                return ResourceManager.GetString("ScanAgainButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ScanBottomText {
            get {
                return ResourceManager.GetString("ScanBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ScanCancelText {
            get {
                return ResourceManager.GetString("ScanCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string ScanFlashText {
            get {
                return ResourceManager.GetString("ScanFlashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan certificate.
        /// </summary>
        public static string ScanTopText {
            get {
                return ResourceManager.GetString("ScanTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test date: .
        /// </summary>
        public static string TestDateLabel {
            get {
                return ResourceManager.GetString("TestDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        public static string TestedText {
            get {
                return ResourceManager.GetString("TestedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        public static string TestHeader {
            get {
                return ResourceManager.GetString("TestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test centre: .
        /// </summary>
        public static string TestingCentreLabel {
            get {
                return ResourceManager.GetString("TestingCentreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test manifacturer: .
        /// </summary>
        public static string TestManifacturerLabel {
            get {
                return ResourceManager.GetString("TestManifacturerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test name: .
        /// </summary>
        public static string TestNameLabel {
            get {
                return ResourceManager.GetString("TestNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result date: .
        /// </summary>
        public static string TestResultDateLabel {
            get {
                return ResourceManager.GetString("TestResultDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result: .
        /// </summary>
        public static string TestResultLabel {
            get {
                return ResourceManager.GetString("TestResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample origin: .
        /// </summary>
        public static string TestSampleOriginLabel {
            get {
                return ResourceManager.GetString("TestSampleOriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test type: .
        /// </summary>
        public static string TestTypeLabel {
            get {
                return ResourceManager.GetString("TestTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliterated name: .
        /// </summary>
        public static string TranNameLabel {
            get {
                return ResourceManager.GetString("TranNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvalid QR code.
        /// </summary>
        public static string UnvalidCode {
            get {
                return ResourceManager.GetString("UnvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public keys needs to be updated.
        /// </summary>
        public static string UpdatePublicKeys {
            get {
                return ResourceManager.GetString("UpdatePublicKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateViewButtonText {
            get {
                return ResourceManager.GetString("UpdateViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version:.
        /// </summary>
        public static string UpdateViewCurrentVersionText {
            get {
                return ResourceManager.GetString("UpdateViewCurrentVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        public static string UpdateViewLatestVersionText {
            get {
                return ResourceManager.GetString("UpdateViewLatestVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back button deactivated, update is mandatory.
        /// </summary>
        public static string UpdateViewPageText {
            get {
                return ResourceManager.GetString("UpdateViewPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your app.
        /// </summary>
        public static string UpdateViewTitle {
            get {
                return ResourceManager.GetString("UpdateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully vaccinated.
        /// </summary>
        public static string VaccinatedText {
            get {
                return ResourceManager.GetString("VaccinatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        public static string VaccinationDateLabel {
            get {
                return ResourceManager.GetString("VaccinationDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccination.
        /// </summary>
        public static string VaccinationHeader {
            get {
                return ResourceManager.GetString("VaccinationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible: .
        /// </summary>
        public static string VaccinationProviderLabel {
            get {
                return ResourceManager.GetString("VaccinationProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth holder: .
        /// </summary>
        public static string VaccineAuthLabel {
            get {
                return ResourceManager.GetString("VaccineAuthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string VaccineDescriptionLabel {
            get {
                return ResourceManager.GetString("VaccineDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch: .
        /// </summary>
        public static string VaccineLotLabel {
            get {
                return ResourceManager.GetString("VaccineLotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string VaccineNameLabel {
            get {
                return ResourceManager.GetString("VaccineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validarion rule version: .
        /// </summary>
        public static string ValidationRulesVersion {
            get {
                return ResourceManager.GetString("ValidationRulesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from: .
        /// </summary>
        public static string ValidFromLabel {
            get {
                return ResourceManager.GetString("ValidFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until: .
        /// </summary>
        public static string ValidUntilLabel {
            get {
                return ResourceManager.GetString("ValidUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string VerificationText {
            get {
                return ResourceManager.GetString("VerificationText", resourceCulture);
            }
        }
    }
}
